variables:
    DOCKER_TAG_DEV: ${CI_COMMIT_REF_NAME}
    DOCKER_IMAGE_DEV: dpsim-service

stages:
- prepare
- test


docker:
    stage: prepare
    script:
        - docker build -t ${DOCKER_IMAGE_DEV}:${DOCKER_TAG_DEV} .
    tags:
        - shell
        - linux

test-dpsimadapter:
    stage: test
    script:
        - pytest -v -cov --junitxml=report.xml test/test_static_analysis_controller.py
    image: ${DOCKER_IMAGE_DEV}:${DOCKER_TAG_DEV}
    tags:
        - docker
    artifacts:
        reports:
            junit: report.xml

format:
    stage: test
    allow_failure: true
    script:
        - flake8 --statistics
    image: ${DOCKER_IMAGE_DEV}:${DOCKER_TAG_DEV}
    tags:
        - docker
