version: "3.8"
services:
  cimpy-server:
    depends_on:
      - redis
    image: "cimpy-server"
    ports:
      - "8081:8080"
    networks:
      cimpy-server:
        aliases:
          - "cimpy-server"
  dpsim-service:
    depends_on:
      - redis
    image: "dpsim-service"
    ports:
      - "8082:8080"
    networks:
      cimpy-server:
        aliases:
          - "dpsim-service"
  redis:
    image: "redis:alpine"
    ports:
      - "6379:6379"
    networks:
      cimpy-server:
        aliases:
          - "redis"

networks:
  cimpy-server:
